-- DISABLED 2026-07-22: the app is now live to real users. This demo seed
-- (friends, games, messages) was only needed for App Store review and would
-- otherwise re-create fake games/users that real users could join.
--
-- The seeded content has been removed from production. Do NOT re-enable on the
-- live database. If pre-populated content is needed for a FUTURE review, seed a
-- throwaway/staging environment instead, or run the seed manually and remove it
-- again before releasing the update.
--
-- (Intentionally a no-op so the deploy migration step stays green.)
SELECT 1;
